#include <PlCode>

const char *pl_codeToStr(PlCode code)
{
    switch (code)
    {
    case PL_CONSTANT:
        return "const";
    case PL_CONSTANT_LONG:
        return "const_long";
    case PL_NULL:
        return "null";
    case PL_TRUE:
        return "true";
    case PL_FALSE:
        return "false";
    case PL_POP:
        return "pop";
    case PL_DUPLICATE:
        return "dup";
    case PL_DUPLICATE_PREV:
        return "dup_prev";
    case PL_GET_LOCAL:
        return "get_loc";
    case PL_SET_LOCAL:
        return "set_loc";
    case PL_GET_GLOBAL:
        return "get_gbl";
    case PL_SET_GLOBAL:
        return "set_gbl";
    case PL_DEFINE_GLOBAL:
        return "def_gbl";
    case PL_GET_SURVALUE:
        return "get_svl";
    case PL_SET_SURVALUE:
        return "set_svl";
    case PL_GET_PROPERTY:
        return "get_prop";
    case PL_SET_PROPERTY:
        return "set_prop";
    case PL_GET_SUPER:
        return "get_sup";
    case PL_GET_INDEX:
        return "get_idx";
    case PL_SET_INDEX:
        return "set_idx";
    case PL_GET_LOCAL_LONG:
        return "get_loc_long";
    case PL_SET_LOCAL_LONG:
        return "set_loc_long";
    case PL_GET_GLOBAL_LONG:
        return "get_gbl_long";
    case PL_DEFINE_GLOBAL_LONG:
        return "def_gbl_long";
    case PL_SET_GLOBAL_LONG:
        return "set_gbl_long";
    case PL_GET_SURVALUE_LONG:
        return "get_svl_long";
    case PL_SET_SURVALUE_LONG:
        return "set_svl_long";
    case PL_GET_PROPERTY_LONG:
        return "get_prop_long";
    case PL_SET_PROPERTY_LONG:
        return "set_prop_long";
    case PL_GET_SUPER_LONG:
        return "get_sup_long";
    case PL_EQUAL:
        return "equ";
    case PL_GREATER:
        return "gre";
    case PL_LESS:
        return "lss";
    case PL_ADD:
        return "add";
    case PL_SUBTRACT:
        return "sub";
    case PL_MULTIPLY:
        return "mul";
    case PL_DIVIDE:
        return "div";
    case PL_MODULO:
        return "mod";
    case PL_NOT:
        return "not";
    case PL_NEGATE:
        return "neg";
    case PL_AFFIRM:
        return "aff";
    case PL_BITNOT:
        return "bitnot";
    case PL_BITAND:
        return "bitand";
    case PL_BITXOR:
        return "bitxor";
    case PL_LSHIFT:
        return "lshift";
    case PL_RSHIFT:
        return "rshift";
    case PL_ADD_1:
        return "add1";
    case PL_DEC_1:
        return "dec1";
    case PL_PRINT:
        return "print";
    case PL_PRINT_EMPTY:
        return "print_empty";
    case PL_JUMP:
        return "jmp";
    case PL_JUMP_IF_FALSE:
        return "jne";
    case PL_LOOP:
        return "loop";
    case PL_CALL:
        return "call";
    case PL_INVOKE:
        return "ivk";
    case PL_SUPER_INVOKE:
        return "siv";
    case PL_CLOSURE:
        return "clo";
    case PL_CLOSE_SURVALUE:
        return "csv";
    case PL_RETURN:
        return "ret";
    case PL_CLASS:
        return "cls";
    case PL_INHERIT:
        return "inher";
    case PL_METHOD:
        return "met";
    case PL_INVOKE_LONG:
        return "ivk_long";
    case PL_SUPER_INVOKE_LONG:
        return "siv_long";
    case PL_CLOSURE_LONG:
        return "clo_long";
    case PL_CLASS_LONG:
        return "cls_long";
    case PL_METHOD_LONG:
        return "met_long";
    case PL_VECTOR:
        return "vec";
    case PL_MAP:
        return "map";
    case PL_SIZEOF:
        return "sizeof";
    default:
        return "unknown";
    }
}
